### ISSUE TITLE
Not able get this self started on self hosted env

### ISSUE THREAD

**Issue by hirani89** [mountain-pass/addressr#364]
Hi there,

Thanks for creating this application.

I have been able to deploy this to azure successfully.

I have a few questions though.

1. How do I fix `NODE_ENV: development|(set NODE_ENV to 'production' in production environments)`
2. How do I keep `addressr-server-2` and `sudo docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.9.2` running without having to keep my ssh sessions alive. Also, these should run in the background and also auto start on boot.

Regards.

**Comment by hirani89** [comment]
Ok. I have managed to "may be" sort things out. Please correct me if there is a better way of doing things.

I am running `addressr-server-2` in `pm2`.

I have created a `docker-compose.yml` file where I have defined `restart: unless-stopped` and specified a volume so that I don't have to run `addressr-loader` every time the server/docker restarts.

Here is my docker-compose file

```
version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
    restart: unless-stopped

volumes:
  esdata:
   driver: local
```
